### ISSUE TITLE
`kiauto_time_out_scale` and `kiauto_wait_start` error - has this got something to do with Docker? 

### ISSUE THREAD

**Issue by anujdeshpande** [nerdyscout/kicad-exports#31]
Hi

I was trying run a simple kicad-exports command with the following config

```yaml
# Example KiBot config file
kibot:
  version: 1

global:
  kiauto_wait_start: 20
  kiauto_time_out_scale: 3.0

preflight:
  run_drc: true
```
I get the following logs when I run the command verbosely. I tried tweaking these values, but still not able to run this without issues. I am wondering if this has something to do with the docker image/settings? How would I go about fixing those?

The computer I am running this on has a recent AMD CPU, and 32 gigabytes of RAM. So I am fairly certain the issue is something other than what's mentioned in the logs

```
> DEBUG:Terminating the session recorder (pcbnew_do.kiauto.ui_automation - ui_automation.py:161)
> DEBUG:Closing pipe with 241 (pcbnew_do.kiauto.ui_automation - ui_automation.py:41)
> DEBUG:Terminating 241 (pcbnew_do.kiauto.ui_automation - ui_automation.py:53)
> Traceback (most recent call last):
>   File "/usr/bin/pcbnew_do", line 715, in <module>
>     run_drc(cfg)
>   File "/usr/bin/pcbnew_do", line 374, in run_drc
>     run_drc_5_1(cfg)
>   File "/usr/bin/pcbnew_do", line 295, in run_drc_5_1
>     wait_for_window('DRC modal window', 'DRC Control')
>   File "/usr/lib/python3/dist-packages/kiauto/ui_automation.py", line 344, in wait_for_window
>     raise RuntimeError('Timed out waiting for %s window' % name)
> RuntimeError: Timed out waiting for DRC modal window window
> DEBUG:Restoring old pcbnew config (pcbnew_do.kiauto.file_util - file_util.py:152)
> DEBUG:Checking if /home/anuj/workdir/balena-fin-PCB.pro was modified (pcbnew_do.kiauto.file_util - file_util.py:242)
>  (kibot.kibot.kiplot - kiplot.py:175)
WARNING:(W054) Time out detected, on slow machines or complex projects try: (kibot.kibot.kiplot - log.py:82)
WARNING:(W054) `kiauto_time_out_scale` and/or `kiauto_wait_start` global options (kibot.kibot.kiplot - log.py:82)
ERROR:DRC returned 1 (kibot.kibot.pre_drc - pre_drc.py:63)
```

**Comment by nerdyscout** [comment]
sounds to me like [issue#86](https://github.com/INTI-CMNB/KiBot/issues/86), is your schematic fully annotated ?

If so there might be an other issue, in that case please provide a sample project for reproduction.
